// The available country codes grouped by region
export const AVAILABLE_COUNTRIES = {
  europe: [
    "AT",
    "BE",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE",
  ],
  northAmerica: [
    "US",
    "CA",
    "MX",
    "BS",
    "BB",
    "CR",
    "DO",
    "GT",
    "HN",
    "NI",
    "PA",
    "SV",
    "CU",
    "JM",
    "HT",
  ],
  asia: [
    "CN",
    "IN",
    "ID",
    "JP",
    "KR",
    "MY",
    "PH",
    "SG",
    "TH",
    "VN",
    "BD",
    "LK",
    "MM",
    "KH",
    "LA",
    "NP",
    "BT",
    "MV",
  ],
  middleEast: [
    "AE",
    "BH",
    "IQ",
    "IR",
    "JO",
    "KW",
    "LB",
    "OM",
    "QA",
    "SA",
    "SY",
    "YE",
  ],
  africa: [
    "DZ",
    "AO",
    "BJ",
    "BW",
    "BF",
    "BI",
    "CM",
    "CV",
    "CF",
    "TD",
    "KM",
    "CD",
    "CG",
    "CI",
    "DJ",
    "GQ",
    "ER",
    "SZ",
    "ET",
    "GA",
    "GM",
    "GH",
    "GN",
    "GW",
    "KE",
    "LS",
    "LR",
    "LY",
    "MG",
    "MW",
    "ML",
    "MR",
    "MU",
    "MA",
    "MZ",
    "NA",
    "NE",
    "NG",
    "RW",
    "ST",
    "SN",
    "SC",
    "SL",
    "SO",
    "ZA",
    "SS",
    "SD",
    "TZ",
    "TG",
    "TN",
    "UG",
    "ZM",
    "ZW",
  ],
  southAmerica: [
    "AR",
    "BO",
    "BR",
    "CL",
    "CO",
    "EC",
    "GY",
    "PY",
    "PE",
    "SR",
    "UY",
    "VE",
  ],
  oceania: [
    "AU",
    "NZ",
    "FJ",
    "PG",
    "SB",
    "VU",
    "NC",
    "PF",
    "WS",
    "KI",
    "TO",
    "TV",
    "NR",
    "MH",
    "FM",
    "PW",
  ],
};

export const COUNTRY_OPTIONS = [
  // Europe
  { value: "AT", label: "Austria" },
  { value: "BE", label: "Belgium" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croatia" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "DK", label: "Denmark" },
  { value: "EE", label: "Estonia" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "GR", label: "Greece" },
  { value: "HU", label: "Hungary" },
  { value: "IE", label: "Ireland" },
  { value: "IT", label: "Italy" },
  { value: "LV", label: "Latvia" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MT", label: "Malta" },
  { value: "NL", label: "Netherlands" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "RO", label: "Romania" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "ES", label: "Spain" },
  { value: "SE", label: "Sweden" },
  // North America
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "MX", label: "Mexico" },
  { value: "BS", label: "Bahamas" },
  { value: "BB", label: "Barbados" },
  { value: "CR", label: "Costa Rica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "GT", label: "Guatemala" },
  { value: "HN", label: "Honduras" },
  { value: "NI", label: "Nicaragua" },
  { value: "PA", label: "Panama" },
  { value: "SV", label: "El Salvador" },
  { value: "CU", label: "Cuba" },
  { value: "JM", label: "Jamaica" },
  { value: "HT", label: "Haiti" },
];
