version: "3.8"

services:
  app:
    image: ghcr.io/thibautrey/referal-tool:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - DEV=${DEV:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - redis
    volumes:
      - ./backend/src:/app/src
      - ./frontend/src:/app/frontend/src
    networks:
      - referal_app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - referal_app-network

volumes:
  redis-data:

networks:
  referal_app-network:
    driver: overlay
    attachable: true
    external: true
