version: "3.8"

services:
  app:
    image: ghcr.io/thibautrey/referal-tool:${IMAGE_TAG:-latest}
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV:-production}
        - REACT_APP_API_URL=${REACT_APP_API_URL:-https://rflnk.com/api}
        - NODE_ENV=${NODE_ENV:-production}
        - APP_URL=${APP_URL:-https://rflnk.com}
        - ILA_LICENSE_KEY=${ILA_LICENSE_KEY}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - DEV=${DEV:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND=${RESEND}
      - APP_URL=${APP_URL:-https://rflnk.com}
      - PROXIES_URL=${PROXIES_URL}
      - ILA_DATA_DIR=/app/data
      - ILA_TMP_DATA_DIR=/app/tmp
      - ILA_LICENSE_KEY=${ILA_LICENSE_KEY}
    # depends_on:
    #   - redis
    volumes:
      - ./backend/src:/app/src:ro
      - ./frontend/src:/app/frontend/src:ro
      - /app/dist
      - ip-data:/app/data
      - ip-tmp:/app/tmp
#   redis:
#     image: redis:7-alpine
#     volumes:
#       - redis-data:/data

volumes:
  ip-data:
  ip-tmp:
