version: "3.8"

services:
  app:
    image: ghcr.io/thibautrey/referal-tool:${IMAGE_TAG:-latest}
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV:-production}
        - REACT_APP_API_URL=${REACT_APP_API_URL:-https://rflnk.com/api}
        - NODE_ENV=${NODE_ENV:-production}
        - APP_URL=${APP_URL:-https://rflnk.com}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - DEV=${DEV:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND=${RESEND}
      - APP_URL=${APP_URL:-https://rflnk.com}
    # depends_on:
    #   - redis
    volumes:
      - ./backend/src:/app/src:ro
      - ./frontend/src:/app/frontend/src:ro
      - /app/dist
#   redis:
#     image: redis:7-alpine
#     volumes:
#       - redis-data:/data

# volumes:
#   redis-data:
