version: "3.8"

services:
  app:
    image: ghcr.io/thibautrey/referal-tool:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - DEV=${DEV:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    volumes:
      - ./backend/src:/app/src:ro
      - ./frontend/src:/app/frontend/src:ro
      - /app/dist
    networks:
      - referal_app-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - referal_app-network

volumes:
  redis-data:
