-- AlterTable
ALTER TABLE `Link` ADD COLUMN `utmCampaign` VARCHAR(191) NULL,
    ADD COLUMN `utmContent` VARCHAR(191) NULL,
    ADD COLUMN `utmMedium` VARCHAR(191) NULL,
    ADD COLUMN `utmSource` VARCHAR(191) NULL,
    ADD COLUMN `utmTerm` VARCHAR(191) NULL;
